### ISSUE TITLE
Update Global.json

### ISSUE THREAD

**Issue by samcov** [microsoft/coyote-samples#11]
I was attempting to load the helloworldactors and the project failed to load, complaining about the .net version.

I looked in the main coyote repo and saw that the global.json specified
{
  "sdk": {
    **"version": "3.1.401"**
  }
}
Where as the samples global.json specified
{
  "sdk": {
    **"version": "3.1.300"**
  }
}
Once I changed to the latest version, the project loaded and compiled without incident.

**Comment by lovettchris** [comment]
Both are now on "version": "3.1.402"
